version: "3"
services:
  #   node:
  #     build: .
  #     ports:
  #      - "8080:8080"
  #     expose:
  #       - "8080"
  #     links:
  #       - mysql
  #     depends_on:
  #       - mysql
  mysql:
    image: "mysql:latest"
    ports:
      - "1111:3306"
    volumes:
      - ../../mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
      MYSQL_DATABASE: "community"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "test1234"
    expose:
      - "1111"
