version: "3"
networks:
  backend:
    driver: bridge
services:
  nginx:
    container_name: nginx
    image: "nginx:test"
    ports:
     - "80:80"
    networks:
     - backend
  node:
    container_name: "node"
    build: .
    ports:
     - "3000:3000"
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    container_name: "mysql"
    image: "mysql:latest"
    ports:
      - "1111:3306"
    volumes:
      - ../../mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "test1234"
      MYSQL_DATABASE: "community"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "test1234"
    expose:
      - "3306"
    networks:
      - backend
